### ISSUE TITLE
CSS transition doesn't happen for elements in view on page load

### ISSUE THREAD

**Issue by ndimatteo** [manGoweb/isinview#1]
👋Hi there!

First off, awesome job with this. I love that you're using the new `IntersectionObserver` for this!

I'm getting super smooth animations on scroll, however I noticed that elements that are visible on screen on page load **do not** show a transition. I'm assuming this is because the `data-can-appear` and the class I'm adding when in view are being added at the same time for those elements.

Anything out of view that's scrolled to animates just fine, but is there a way to have items that are "inview" on page load play out their transition?

Here's how I'm initializing:

```javascript
if (isSupported()) {
  const $anim = $("[data-appear]");
  $anim.attr("data-can-appear", "");
  isInView($anim, target => {
    target.classList.add("is-appeared");
  });
}
```

And here's my CSS:
```css
[data-can-appear] {
  opacity: 0;
  transform: translate3d(0, 2.5rem, 0);
  transition: opacity 0.5s linear,
    transform 1.25s cubic-bezier(0.23, 1, 0.32, 1);
  transition-delay: 0.2s;

  &.is-appeared {
    opacity: 1;
    transform: none;
  }
}
```

**Comment by FilipChalupa** [comment]
I like your approach and keeping in mind unsupported browsers and with disabled javascript. :+1:

It's as you say. `[data-can-appear]` and `.is-appeared` are added at the same time.

In your case delaying `isInView` initialization or forcing layout/reflow just before init should do the trick.

```javascript
if (isSupported()) {
  const $anim = $("[data-appear]");
  $anim.attr("data-can-appear", "");
  requestAnimationFrame(() => {
    isInView($anim, target => {
      target.classList.add("is-appeared");
    });
  });
}
```

**Comment by ndimatteo** [comment]
Thanks @Onset !

I gave your code example a quick test, but no dice. It seems `requestAnimationFrame` doesn't jig it. If you have any other suggestions I'm all ears!

**Comment by FilipChalupa** [comment]
I see. I was wrong. The problem is in CSS.

Elements load with `opacity: 1` (initial value). Then `[data-can-appear]` with `opacity: 0` and some transform is added. Elements starts to fade out. `isInView` adds `.is-appeared` with `opacity: 1`. The time to go from `1` to `0` to `1` is so quick you don't even see a short flash.

Try moving `transition` to `.is-appeared`.

```css
[data-can-appear] {
  opacity: 0;
  transform: translate3d(0, 2.5rem, 0);

  &.is-appeared {
    opacity: 1;
    transform: none;
    transition: opacity 0.5s linear, transform 1.25s cubic-bezier(0.23, 1, 0.32, 1);
    transition-delay: 0.2s;
  }
}
```
